INSERT INTO GENRE (id, NAME) VALUES (1, 'Comedy');
INSERT INTO GENRE (id, NAME) VALUES (2, 'Drama');
INSERT INTO GENRE (id, NAME) VALUES (3, 'Animation');
INSERT INTO GENRE (id, NAME) VALUES (4, 'Thriller');
INSERT INTO GENRE (id, NAME) VALUES (5, 'Documentary');
INSERT INTO GENRE (id, NAME) VALUES (6, 'Action');

INSERT INTO RATING (id, NAME) VALUES (1, 'G');
INSERT INTO RATING (id, NAME) VALUES (2, 'PG');
INSERT INTO RATING (id, NAME) VALUES (3, 'PG-13');
INSERT INTO RATING (id, NAME) VALUES (4, 'R');
INSERT INTO RATING (id, NAME) VALUES (5, 'NC-17');
