CREATE TABLE CLIENT
(
    ID       INTEGER NOT NULL AUTO_INCREMENT,
    EMAIL    CHARACTER VARYING,
    LOGIN    CHARACTER VARYING,
    NAME     CHARACTER VARYING,
    BIRTHDAY DATE,
    FRIENDS  INTEGER,
    CONSTRAINT CONSTRAINT_7 PRIMARY KEY (ID)
);

CREATE TABLE FRIEND
(
    CLIENT_ID   INTEGER NOT NULL,
    FRIEND_ID INTEGER NOT NULL,
    STATUS    BOOLEAN,
    CONSTRAINT CONSTRAINT_706 PRIMARY KEY (FRIEND_ID, CLIENT_ID),
    CONSTRAINT CONSTRAINT_70 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT CONSTRAINT_707 FOREIGN KEY (FRIEND_ID) REFERENCES CLIENT (ID) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE GENRE
(
    ID   INTEGER NOT NULL AUTO_INCREMENT,
    NAME CHARACTER VARYING,
    CONSTRAINT CONSTRAINT_4 PRIMARY KEY (ID)
);

CREATE TABLE RATING
(
    ID   INTEGER NOT NULL AUTO_INCREMENT,
    NAME CHARACTER VARYING,
    CONSTRAINT CONSTRAINT_8 PRIMARY KEY (ID)
);

CREATE TABLE FILM
(
    ID           INTEGER NOT NULL AUTO_INCREMENT,
    NAME         CHARACTER VARYING,
    DESCRIPTION  CHARACTER VARYING,
    RELEASE_DATE TIMESTAMP,
    DURATION     INTEGER,
    LIKES        INTEGER,
    GENRE        INTEGER,
    RATING       INTEGER,
    CONSTRAINT CONSTRAINT_2 PRIMARY KEY (ID),
    CONSTRAINT CONSTRAINT_20 FOREIGN KEY (GENRE) REFERENCES GENRE (ID) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT CONSTRAINT_20E FOREIGN KEY (RATING) REFERENCES RATING (ID) ON DELETE SET NULL ON UPDATE RESTRICT
);

CREATE TABLE Likes (
    FILM_ID INTEGER NOT NULL,
    CLIENT_ID INTEGER NOT NULL,
    FOREIGN KEY(FILM_ID) REFERENCES FILM(ID),
    FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(ID),
    PRIMARY KEY (FILM_ID, CLIENT_ID)
);