CREATE TABLE PUBLIC.CLIENT
(
    ID       INTEGER NOT NULL AUTO_INCREMENT,
    EMAIL    CHARACTER VARYING,
    LOGIN    CHARACTER VARYING,
    NAME     CHARACTER VARYING,
    BIRTHDAY TIMESTAMP,
    FRIENDS  INTEGER,
    CONSTRAINT CONSTRAINT_7 PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.FRIENDS
(
    USER_ID   INTEGER NOT NULL,
    FRIEND_ID INTEGER NOT NULL,
    STATUS    BOOLEAN,
    CONSTRAINT CONSTRAINT_70 PRIMARY KEY (USER_ID),
    CONSTRAINT CONSTRAINT_706 PRIMARY KEY (FRIEND_ID, USER_ID),
    CONSTRAINT CONSTRAINT_70 FOREIGN KEY (USER_ID) REFERENCES PUBLIC.CLIENT (ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE PUBLIC.GENRE
(
    ID   INTEGER NOT NULL AUTO_INCREMENT,
    NAME CHARACTER VARYING,
    CONSTRAINT CONSTRAINT_4 PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.RATING
(
    ID   INTEGER NOT NULL AUTO_INCREMENT,
    NAME CHARACTER VARYING,
    CONSTRAINT CONSTRAINT_8 PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.FILM
(
    ID           INTEGER NOT NULL AUTO_INCREMENT,
    NAME         CHARACTER VARYING,
    DESCRIPTION  CHARACTER VARYING,
    RELEASE_DATE TIMESTAMP,
    DURATION     INTEGER,
    LIKES        INTEGER,
    GENRE        INTEGER,
    RATING       INTEGER,
    CONSTRAINT CONSTRAINT_2 PRIMARY KEY (ID),
    CONSTRAINT CONSTRAINT_20 PRIMARY KEY (ID, GENRE),
    CONSTRAINT CONSTRAINT_20E PRIMARY KEY (ID, RATING),
    CONSTRAINT CONSTRAINT_20 FOREIGN KEY (GENRE) REFERENCES PUBLIC.GENRE (ID) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT CONSTRAINT_20E FOREIGN KEY (RATING) REFERENCES PUBLIC.RATING (ID) ON DELETE SET NULL ON UPDATE RESTRICT
);